version: '3.9'

services:
  cinemapub:
    image: cinemapub
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python CinemaPub/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app